### ISSUE TITLE
implement apidocs legacy-api into new docs theme

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/docs#1]
Acc. Crit.:
- layout/theme aligned with getting started docs
- searchable
- new major navigation heading on left navigation pane

**Comment by ZNicoZ** [comment]
There is a tool for markdown output:
https://github.com/tom-grey/typedoc-plugin-markdown

**Comment by svettwer** [comment]
Already done: https://sakuli.io/docs/writing_tests/webtests/#accessors-by-html-tag-or-attributes
