### ISSUE TITLE
Add Logger documentation

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/docs#4]
- How to log to sakuli.log
- How to log to the console
- How to set log-level

Acc. Crit.:
- [ ] add log documentation to cookbook
- [ ] Includes: how to use the logger instance, how to configure logging, how to log to console

**Comment by tnobody** [comment]
Also explain logging property: `sakuli.log.folder` (as CLI parameter and property in property file)

**Comment by ZNicoZ** [comment]
sakuli.log.folder will be covered in sakuli/docs#12
