### ISSUE TITLE
Restructure sections in docs

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/docs#50]
Currently our docs are a bit inconsistent in terms of content.

Some sections only hold a single header which displays everything at once (e.g. "Configuring Tests") while others hold content on header pages but also have additional subpages.

Since the overall docs theme is meant to serve as a "click-through" document we should restructure our docs so each section header only provides a short, high-level description of what will be discussed in upcoming subsections. Content should be moved to subsections for consistency.

**Comment by svettwer** [comment]
It would be great if you could propose a structure so that we can discuss it.

**Comment by svettwer** [comment]
closed for now. If this becomes important again in the future, please open a new issue.
